LIBS = -lxml2

CC = x86_64-w64-mingw32-g++
CFLAGS = -MMD -Wall -O3 -std=c++14 -static-libgcc -static-libstdc++ -L./windep/lib -Isrc -I./windep/include
OUTPUT = pharmml2poped.exe

pharmmltool: utils/pharmmltool.cpp
	$(CC) utils/pharmmltool.cpp -opharmmltool `xml2-config --libs --cflags`

.PHONY: install
install:
	cp pharmmltool /usr/bin
	mkdir -p /usr/share/libpharmmlcpp
	cp -rf pharmml_internalRelease_0_8_1 /usr/share/libpharmmlcpp

.PHONY: release
release:
	mkdir -p release
	cp pharmml2poped.exe release
	cp windep/lib/*.dll release
	cp -r pharmml_internalRelease_0_8_1 release
